const KEY='kimu-task-web-v1';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const seed={tasks:[],workdays:[],links:[],imageMemos:[],favorites:[],settings:{endTime:'19:00',shareURL:'https://x.gd/hrRag',includeURL:false,compactRows:false,showDates:true,showTimes:true},groups:{schedule:true,progress:true,genre:false,settings:false}};
const clone=value=>JSON.parse(JSON.stringify(value));
let state=load(), page='today';
state={...clone(seed),...state,tasks:Array.isArray(state?.tasks)?state.tasks:[],workdays:Array.isArray(state?.workdays)?state.workdays:[],links:Array.isArray(state?.links)?state.links:[],imageMemos:Array.isArray(state?.imageMemos)?state.imageMemos:[],favorites:Array.isArray(state?.favorites)?state.favorites:[],settings:{...seed.settings,...(state?.settings||{})},groups:{...seed.groups,...(state?.groups||{})}};
let cloudClient=null, cloudUser=null;
let cloudApplying=false, cloudBusy=false;
const cloudDefaults={url:'https://qlepvmxyinathcicesfv.supabase.co',key:'sb_publishable_PkdyTEB-pvuchkJqm3f7Pw_8GGJK4Au'};
let cloudConfig={...cloudDefaults,...JSON.parse(localStorage.getItem('kimu-cloud-config')||'{}')};
const deviceID=localStorage.getItem('kimu-device-id')||uid();
localStorage.setItem('kimu-device-id',deviceID);
const $=s=>document.querySelector(s), content=$('#content');
function load(){try{return {...clone(seed),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return clone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent=cloudUser?'● 端末に保存・同期待ち':'● 保存済み'}
function dirty(){
 localStorage.setItem('kimu-local-updated-at',new Date().toISOString());
 $('#saveState').textContent='○ 保存中';clearTimeout(dirty.t);dirty.t=setTimeout(()=>{save();scheduleCloudPush()},180)
}
function scheduleCloudPush(){if(!cloudUser||cloudApplying)return;clearTimeout(scheduleCloudPush.t);scheduleCloudPush.t=setTimeout(()=>pushCloudState(true),1400)}
const statusInfo={urgent:['★絶対今日','絶対今日'],early:['早め','早め'],mid:['できればやる','中期'],long:['いつかやる','長期'],wait:['まち','まち'],hold:['一時保留','一時保留'],done:['完了','完了']};
const navGroups=[
 {id:'memo',title:'メモ',fixed:true,items:[['idea','💡','思いつきBOX','idea'],['memo','📝','仕事メモ','memo'],['imageMemo','🖼','画像メモ','image'],['links','🔗','よく使うリンク集']]},
 {id:'schedule',title:'予定管理',items:[['working','▶','いま作業中'],['timeline','◷','タイムライン'],['calendar','▣','カレンダー'],['notifications','🔔','通知一覧'],['attendance','◉','出退勤管理'],['review','▥','今日の振り返り'],['tomorrow','☀','明日の予定'],['dailyPlan','🌅','朝・夕方の整理'],['line','💬','LINE用 今日の仕事']]},
 {id:'progress',title:'進行状況',items:[['all','☷','すべて'],['today','☀','今日'],['mid','▣','中期'],['long','◴','長期'],['wait','Ⅱ','まち'],['done','✓','完了'],['hold','□','一時保留']]},
 {id:'genre',title:'ジャンル',items:[['genres','▤','すべて']]},
 {id:'settings',title:'設定',items:[['favorites','☆','よく使う仕事'],['archive','▣','アーカイブ'],['trash','♲','ゴミ箱'],['sync','↻','同期設定'],['backup','⇩','バックアップ'],['display','☷','表示設定'],['legend','🎨','色の凡例'],['diagnostics','♡','診断']]}
];
function renderNav(){
 $('#nav').innerHTML=`<div class="nav-top"><button class="nav-item ${page==='pickup'?'active':''}" data-page="pickup">⭐ ピックアップ</button></div>`+navGroups.map(g=>`<section class="nav-group ${!g.fixed&&!state.groups[g.id]?'closed':''}" data-group="${g.id}"><button class="group-toggle">${g.title}</button><div class="nav-children">${g.items.map(i=>`<div class="nav-row"><button class="nav-item ${page===i[0]?'active':''}" data-page="${i[0]}"><span>${i[1]}</span>${i[2]}</button>${i[3]?`<button class="quick-add" data-quick="${i[3]}" aria-label="${i[2]}へ追加">＋</button>`:''}</div>`).join('')}${g.id==='genre'?categories().map(c=>`<button class="nav-item ${page==='cat:'+c?'active':''}" data-page="cat:${esc(c)}"><span style="color:${categoryColor(c)}">●</span>${esc(c)}</button>`).join(''):''}</div></section>`).join('');
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;closeSidebar();render()});
 document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.quick==='image'){page='imageMemo';closeSidebar();render();setTimeout(()=>$('#imageFile')?.click(),0)}else openTask(null,b.dataset.quick)});
 document.querySelectorAll('.group-toggle').forEach(b=>b.onclick=()=>{const g=b.closest('.nav-group'),id=g.dataset.group;if(id==='memo')return;state.groups[id]=!state.groups[id];dirty();renderNav()});
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=()=>[...new Set(state.tasks.map(t=>t.category).filter(Boolean))];
const categoryColor=s=>`hsl(${[...s].reduce((a,c)=>a+c.charCodeAt(0),0)%360} 55% 48%)`;
const isDate=(t,d)=>t.date===d;
function activeTasks(){return state.tasks.filter(t=>!t.done&&!t.deletedAt&&!t.archivedAt)}
function tasksForPage(){let a=activeTasks(); if(page==='idea')return a.filter(t=>t.kind==='idea');if(page==='memo')return a.filter(t=>t.kind==='memo');a=a.filter(t=>!t.kind);if(page==='today')return a.filter(t=>['★絶対今日','早め'].includes(t.status)&&isDate(t,today()));if(page==='mid')return a.filter(t=>t.status==='できればやる');if(page==='long')return a.filter(t=>t.status==='いつかやる');if(page==='wait')return a.filter(t=>t.status==='まち');if(page==='hold')return a.filter(t=>t.status==='一時保留');if(page==='done')return state.tasks.filter(t=>t.done&&!t.deletedAt);if(page==='tomorrow'){const d=new Date();d.setDate(d.getDate()+1);return a.filter(t=>isDate(t,d.toISOString().slice(0,10)))}if(page.startsWith('cat:'))return a.filter(t=>t.category===page.slice(4));if(page==='working')return a.filter(t=>t.startedAt);if(page==='pickup')return a.filter(t=>t.pinned||t.reminder);return a}
function render(){renderNav();const titles={pickup:'ピックアップ',idea:'思いつきBOX',memo:'仕事メモ',imageMemo:'画像メモ',links:'よく使うリンク集',all:'進行状況：すべて',today:'今日',mid:'中期',long:'長期',wait:'まち',hold:'一時保留',done:'完了',working:'いま作業中',timeline:'タイムライン',calendar:'カレンダー',notifications:'通知一覧',attendance:'出退勤管理',review:'今日の振り返り',tomorrow:'明日の予定',dailyPlan:'朝・夕方の整理',line:'LINE用 今日の仕事',genres:'ジャンル：すべて',favorites:'よく使う仕事',archive:'アーカイブ',sync:'同期設定',backup:'バックアップ',trash:'ゴミ箱',display:'表示設定',legend:'色の凡例',diagnostics:'診断'};$('#pageTitle').textContent=page.startsWith('cat:')?page.slice(4):(titles[page]||'Kimu Task');$('#pageSub').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
 document.body.classList.toggle('compact',!!state.settings.compactRows);if(page==='attendance')return renderAttendance();if(page==='line')return renderLine();if(page==='imageMemo')return renderImageMemos();if(page==='links')return renderLinks();if(page==='review')return renderReview();if(page==='calendar')return renderCalendar();if(page==='timeline')return renderTimeline();if(page==='dailyPlan')return renderDailyPlan();if(['backup','sync','favorites','notifications','trash','archive','display','legend','diagnostics'].includes(page))return renderUtility();renderTasks();}
function renderTasks(){const tasks=tasksForPage();const doneToday=state.tasks.filter(t=>t.done&&t.completedAt?.startsWith(today())).length;content.innerHTML=`<div class="summary"><div class="metric"><small>表示中</small><strong>${tasks.length}件</strong></div><div class="metric"><small>予定時間</small><strong>${tasks.reduce((a,t)=>a+(+t.minutes||0),0)}分</strong></div><div class="metric"><small>今日の完了</small><strong>${doneToday}件</strong></div></div><div class="task-list">${tasks.length?tasks.map(taskRow).join(''):'<div class="empty">ここにはまだ何もないよ</div>'}</div>`;bindTaskEvents()}
function taskRow(t){const cls=t.status==='★絶対今日'?'urgent':t.status==='早め'?'early':t.status==='できればやる'?'mid':'';return `<article class="task" data-id="${t.id}"><button class="check ${t.done?'done':''}" aria-label="完了">${t.done?'✓':''}</button><div class="task-main">${t.image?`<img class="task-thumb" src="${t.image}" alt="">`:''}<h3>${esc(t.title)}</h3><div class="meta"><span class="pill" style="color:${categoryColor(t.category||'memo')}">${esc(t.category||'memo')}</span><span class="pill ${cls}">${esc(t.status||'未設定')}</span>${state.settings.showDates!==false?`<span>${esc(t.date||'')}</span>`:''}</div></div>${state.settings.showTimes!==false?`<span class="time">${t.minutes?`${t.minutes}分`:''}</span>`:''}</article>`}
function bindTaskEvents(){document.querySelectorAll('.task').forEach(r=>{r.querySelector('.check').onclick=e=>{e.stopPropagation();const t=state.tasks.find(x=>x.id===r.dataset.id);t.done=!t.done;t.completedAt=t.done?new Date().toISOString():null;dirty();render()};r.onclick=()=>openTask(state.tasks.find(x=>x.id===r.dataset.id))})}
function openTask(task=null,kind=null){const t=task?{...task}:{id:uid(),title:'',category:kind?'memo':'作業・雑務',status:kind==='idea'?'思いつき':kind==='memo'?'仕事メモ':'早め',date:today(),minutes:'',note:'',kind};const f=$('#taskForm');f.innerHTML=`<h2>${task?'仕事内容を編集':'新しく追加'}</h2><div class="field"><label>仕事内容</label><input name="title" value="${esc(t.title)}" required autofocus></div><div class="field"><label>ジャンル</label><input name="category" value="${esc(t.category||'')}"></div><div class="field"><label>進行状況</label><select name="status">${['★絶対今日','早め','できればやる','いつかやる','毎日・定期','まち','一時保留','仕事メモ','思いつき'].map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>時間（分）</label><input name="minutes" type="number" step="5" value="${esc(t.minutes||'')}"></div><div class="field"><label>作業日</label><input name="date" type="date" value="${esc(t.date||today())}"></div><div class="field"><label>メモ</label><textarea name="note">${esc(t.note||'')}</textarea></div><menu>${task?'<button type="button" class="danger" id="deleteTask">削除</button>':''}<button value="cancel" class="secondary">戻る</button><button value="save" class="primary">保存</button></menu>`;f.onsubmit=e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const data=Object.fromEntries(new FormData(f));Object.assign(t,data,{minutes:data.minutes?+data.minutes:null});const i=state.tasks.findIndex(x=>x.id===t.id);i<0?state.tasks.unshift(t):state.tasks[i]=t;dirty();$('#taskDialog').close();render()};$('#deleteTask')?.addEventListener('click',()=>{const i=state.tasks.findIndex(x=>x.id===t.id);state.tasks[i].deletedAt=new Date().toISOString();dirty();$('#taskDialog').close();render()});$('#taskDialog').showModal()}
function renderAttendance(){let w=state.workdays.find(x=>x.date===today())||{id:uid(),date:today(),clockIn:'',clockOut:'',breakMinutes:120,note:''};const histories=[...state.workdays].sort((a,b)=>b.date.localeCompare(a.date));content.innerHTML=`<div class="attendance-grid"><section class="panel"><h2>今日の出退勤</h2><div class="row"><button class="primary" id="clockIn">出勤</button><button class="primary" id="clockOut">退勤</button></div><div class="field"><label>出勤時刻</label><input id="inTime" type="time" value="${w.clockIn||''}"></div><div class="field"><label>退勤時刻</label><input id="outTime" type="time" value="${w.clockOut||''}"></div><div class="field"><label>休憩合計</label><input id="breakMinutes" type="number" step="5" value="${w.breakMinutes}"></div><div class="field"><label>勤務メモ</label><textarea id="workNote">${esc(w.note)}</textarea></div><p class="meta">基本休憩：10:30〜10:45 / 12:00〜13:15 / 15:00〜15:15 / 17:00〜17:15</p></section><section class="panel"><h2>日別履歴</h2>${histories.length?histories.map(x=>`<div class="row spread" style="padding:9px 0;border-bottom:1px solid var(--line)"><span>${x.date}</span><strong>${x.clockIn||'--:--'}〜${x.clockOut||'勤務中'}</strong><button class="secondary copy-work" data-in="${x.clockIn||''}" data-out="${x.clockOut||''}">2セルコピー</button></div>`).join(''):'<p class="empty">履歴はまだないよ</p>'}</section></div>`;const up=()=>{w.clockIn=$('#inTime').value;w.clockOut=$('#outTime').value;w.breakMinutes=+$('#breakMinutes').value;w.note=$('#workNote').value;const i=state.workdays.findIndex(x=>x.date===today());i<0?state.workdays.push(w):state.workdays[i]=w;dirty()};$('#clockIn').onclick=()=>{$('#inTime').value=new Date().toTimeString().slice(0,5);up();renderAttendance()};$('#clockOut').onclick=()=>{$('#outTime').value=new Date().toTimeString().slice(0,5);up();renderAttendance()};['inTime','outTime','breakMinutes','workNote'].forEach(id=>$('#'+id).onchange=up);document.querySelectorAll('.copy-work').forEach(b=>b.onclick=()=>copyText(`${b.dataset.in}\t${b.dataset.out}`,'2セル用にコピーしたよ'))}
function renderLine(){const s=state.settings;content.innerHTML=`<section class="panel"><div class="row spread"><h2>LINE用 今日の仕事</h2><button class="primary" id="copyLine">コピー</button></div><div class="row"><label>終了時間 <input id="endTime" type="time" value="${s.endTime}"></label><label><input id="includeURL" type="checkbox" ${s.includeURL?'checked':''}> リンクを付ける</label><input id="shareURL" value="${esc(s.shareURL)}" style="flex:1" ${s.includeURL?'':'disabled'}></div><textarea id="lineOutput" class="editor line-output">${esc(makeLine())}</textarea></section>`;const refresh=()=>{s.endTime=$('#endTime').value;s.includeURL=$('#includeURL').checked;s.shareURL=$('#shareURL').value;$('#shareURL').disabled=!s.includeURL;$('#lineOutput').value=makeLine();dirty()};['endTime','includeURL','shareURL'].forEach(id=>$('#'+id).onchange=refresh);$('#copyLine').onclick=()=>copyText($('#lineOutput').value,'LINE用文面をコピーしたよ')}
function renderImageMemos(){state.imageMemos=state.imageMemos||[];content.innerHTML=`<section class="panel"><h2>画像をメモ</h2><div class="image-form"><label class="image-picker">📷 写真を選ぶ／撮る<input id="imageFile" type="file" accept="image/*" capture="environment" hidden></label><input id="imageTitle" placeholder="タイトル（あとからでもOK）"><textarea id="imageNote" placeholder="メモ"></textarea><button id="saveImageMemo" class="primary" disabled>画像メモへ追加</button></div><p class="meta">端末内保存では容量を抑えるため画像を自動で縮小するよ。</p></section><section class="image-grid">${state.imageMemos.map(m=>`<article class="image-card" data-id="${m.id}"><img src="${m.image}" alt=""><div><strong>${esc(m.title||'画像メモ')}</strong><p>${esc(m.note||'')}</p><small>${new Date(m.createdAt).toLocaleString('ja-JP')}</small></div><div class="row"><button class="primary move-idea">思いつきBOXへ</button><button class="danger delete-image">削除</button></div></article>`).join('')||'<div class="panel empty">写真やスクリーンショットを、忘れる前に置いておけるよ</div>'}</section>`;let pendingImage='';$('#imageFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;pendingImage=await compressImage(file);$('#saveImageMemo').disabled=false;toast('画像を準備したよ')};$('#saveImageMemo').onclick=()=>{if(!pendingImage)return;state.imageMemos.unshift({id:uid(),image:pendingImage,title:$('#imageTitle').value.trim(),note:$('#imageNote').value.trim(),createdAt:new Date().toISOString()});dirty();renderImageMemos()};document.querySelectorAll('.image-card').forEach(card=>{const memo=state.imageMemos.find(m=>m.id===card.dataset.id);card.querySelector('.move-idea').onclick=()=>{state.tasks.unshift({id:uid(),title:memo.title||'画像メモ',category:'memo',status:'思いつき',date:today(),note:memo.note||'',kind:'idea',image:memo.image});state.imageMemos=state.imageMemos.filter(m=>m.id!==memo.id);dirty();renderImageMemos();toast('思いつきBOXへ移動したよ')};card.querySelector('.delete-image').onclick=()=>{state.imageMemos=state.imageMemos.filter(m=>m.id!==memo.id);dirty();renderImageMemos()}})}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}
function renderLinks(){state.links=state.links||[];content.innerHTML=`<section class="panel"><h2>リンクを追加</h2><div class="link-form"><input id="linkTitle" placeholder="タイトル（例：元スプレッド）"><input id="linkURL" type="url" placeholder="https://"><button id="addLink" class="primary">追加</button></div></section><section class="link-grid">${state.links.map(l=>`<article class="link-card" data-id="${l.id}"><a href="${esc(l.url)}" target="_blank" rel="noopener"><span>🔗</span><div><strong>${esc(l.title)}</strong><small>${esc(l.url)}</small></div></a><div class="row"><button class="secondary edit-link">編集</button><button class="danger delete-link">削除</button></div></article>`).join('')||'<div class="panel empty">よく使うページを登録しておくと、ここからすぐ開けるよ</div>'}</section>`;$('#addLink').onclick=()=>{const title=$('#linkTitle').value.trim(),url=$('#linkURL').value.trim();if(!title||!url)return toast('タイトルとURLを入力してね');state.links.push({id:uid(),title,url});dirty();renderLinks()};document.querySelectorAll('.link-card').forEach(card=>{const link=state.links.find(l=>l.id===card.dataset.id);card.querySelector('.edit-link').onclick=()=>{const title=prompt('タイトル',link.title);if(title===null)return;const url=prompt('URL',link.url);if(url===null)return;link.title=title.trim();link.url=url.trim();dirty();renderLinks()};card.querySelector('.delete-link').onclick=()=>{state.links=state.links.filter(l=>l.id!==link.id);dirty();renderLinks()}})}
function makeLine(){const group=(h,s)=>`【${h}】\n${activeTasks().filter(t=>t.date===today()&&t.status===s).map(t=>'●'+t.title).join('\n')||'（なし）'}`;let out=[group('絶対今日','★絶対今日'),group('早め','早め'),group('今日やりたいこと','できればやる'),`（${state.settings.endTime}）`];if(state.settings.includeURL&&state.settings.shareURL)out.push(state.settings.shareURL);return out.join('\n\n')}
function renderReview(){const done=state.tasks.filter(t=>t.done&&t.completedAt?.startsWith(today())),remain=activeTasks().filter(t=>t.date===today());content.innerHTML=`<div class="summary"><div class="metric"><small>完了</small><strong>${done.length}件</strong></div><div class="metric"><small>完了時間</small><strong>${done.reduce((a,t)=>a+(+t.minutes||0),0)}分</strong></div><div class="metric"><small>残り</small><strong>${remain.length}件</strong></div></div><section class="panel"><h2>完了した仕事</h2>${done.map(t=>`<p>✓ ${esc(t.title)}</p>`).join('')||'<p class="meta">まだないよ</p>'}</section><section class="panel"><h2>残った仕事</h2>${remain.map(t=>`<p>• ${esc(t.title)}</p>`).join('')||'<p class="meta">なし</p>'}</section>`}
function renderCalendar(){const ds=[...new Set(state.tasks.map(t=>t.date).filter(Boolean))].sort();content.innerHTML=`<section class="panel"><h2>日付ごとの予定</h2>${ds.map(d=>`<h3>${d}</h3>${state.tasks.filter(t=>t.date===d&&!t.deletedAt).map(t=>`<p>${t.done?'✓':'○'} ${esc(t.title)}</p>`).join('')}`).join('')||'<p class="empty">予定はまだないよ</p>'}</section>`}
function renderTimeline(){const ts=activeTasks().filter(t=>t.date===today()).sort((a,b)=>(a.order||0)-(b.order||0));let cursor=new Date(),rows=ts.map(t=>{const start=cursor.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});cursor=new Date(cursor.getTime()+(+t.minutes||15)*60000);return `<div class="task"><span class="time">${start}</span><div><h3>${esc(t.title)}</h3><div class="meta">${t.minutes||15}分</div></div></div>`}).join('');content.innerHTML=`<section class="panel"><h2>現在からの予定</h2><div class="task-list">${rows||'<div class="empty">今日の仕事を登録してね</div>'}</div></section>`}
function renderUtility(){if(page==='sync'){const last=localStorage.getItem('kimu-last-cloud-sync');content.innerHTML=`<section class="panel"><h2>Supabase自動同期</h2><p>${cloudUser?`接続中：${esc(cloudUser.email||'ログイン済み')}`:'Mac・iPhone・Webで同じ内容を使うための接続設定だよ。'}</p><div class="field"><label>Project URL</label><input id="cloudURL" value="${esc(cloudConfig.url||'')}" placeholder="https://xxxx.supabase.co"></div><div class="field"><label>Publishable key</label><input id="cloudKey" value="${esc(cloudConfig.key||'')}" placeholder="sb_publishable_... / anon key"></div><div class="field"><label>メール</label><input id="cloudEmail" type="email" value="${esc(cloudConfig.email||'')}"></div><div class="field"><label>パスワード</label><input id="cloudPassword" type="password" autocomplete="current-password"></div><div class="row"><button id="connectCloud" class="primary">${cloudUser?'再接続':'接続'}</button><button id="pushCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ保存</button><button id="pullCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ読込</button></div><p id="cloudStatus" class="meta">${last?'最終同期：'+new Date(last).toLocaleString('ja-JP'):'接続後は起動時に読込、変更後に自動保存するよ。'} パスワードは保存しないよ。</p></section>`;$('#connectCloud').onclick=connectCloud;$('#pushCloud').onclick=()=>pushCloudState(false);$('#pullCloud').onclick=()=>pullCloudState(false)}else if(page==='backup'){content.innerHTML=`<section class="panel"><h2>バックアップ</h2><div class="row"><button id="downloadBackup" class="primary">JSONを書き出す</button><label class="secondary">JSONを読み込む<input id="restoreBackup" type="file" accept="application/json" hidden></label></div></section>`;$('#downloadBackup').onclick=downloadBackup;$('#restoreBackup').onchange=restoreBackup}else if(page==='trash'){const ts=state.tasks.filter(t=>t.deletedAt);content.innerHTML=`<div class="task-list">${ts.map(t=>`<article class="task"><span>♲</span><div><h3>${esc(t.title)}</h3></div><button class="secondary restore" data-id="${t.id}">戻す</button></article>`).join('')||'<div class="empty">ゴミ箱は空だよ</div>'}</div>`;document.querySelectorAll('.restore').forEach(b=>b.onclick=()=>{state.tasks.find(t=>t.id===b.dataset.id).deletedAt=null;dirty();render()})}else content.innerHTML='<section class="panel"><h2>準備中</h2><p>Mac版とつながる形で順番に追加していくよ。</p></section>'}
function renderDailyPlan(){const items=activeTasks().filter(t=>isDate(t,today()));content.innerHTML=`<section class="panel"><h2>${new Date().getHours()<15?'今日の順番を整えよう':'残った仕事を整理しよう'}</h2><p class="meta">朝は今日の確認、夕方は明日へ送る仕事を選べるよ。</p>${items.map(t=>`<div class="row spread daily-item" data-id="${t.id}"><span>${esc(t.title)}</span><button class="secondary move-tomorrow">明日へ</button></div>`).join('')||'<p class="empty">今日の仕事はないよ</p>'}</section>`;document.querySelectorAll('.daily-item').forEach(row=>row.querySelector('.move-tomorrow').onclick=()=>{const d=new Date();d.setDate(d.getDate()+1);state.tasks.find(t=>t.id===row.dataset.id).date=d.toISOString().slice(0,10);dirty();renderDailyPlan();toast('明日の予定へ移動したよ')})}
function renderUtilityV2(){
 if(page==='sync'){const last=localStorage.getItem('kimu-last-cloud-sync');content.innerHTML=`<section class="panel"><h2>Supabase自動同期</h2><p>${cloudUser?`接続中：${esc(cloudUser.email||'ログイン済み')}`:'Mac・iPhone・Webで同じ内容を使うための接続設定だよ。'}</p><div class="field"><label>Project URL</label><input id="cloudURL" value="${esc(cloudConfig.url||'')}"></div><div class="field"><label>Publishable key</label><input id="cloudKey" type="password" value="${esc(cloudConfig.key||'')}"></div><div class="field"><label>メール</label><input id="cloudEmail" type="email" value="${esc(cloudConfig.email||'')}"></div><div class="field"><label>パスワード</label><input id="cloudPassword" type="password" autocomplete="current-password"></div><div class="row"><button id="connectCloud" class="primary">${cloudUser?'再接続':'接続'}</button><button id="pushCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ保存</button><button id="pullCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ読込</button></div><p id="cloudStatus" class="meta">${last?'最終同期：'+new Date(last).toLocaleString('ja-JP'):'接続後は起動時に読込、変更後に自動保存するよ。'} パスワードは保存しないよ。</p></section>`;$('#connectCloud').onclick=connectCloud;$('#pushCloud').onclick=()=>pushCloudState(false);$('#pullCloud').onclick=()=>pullCloudState(false);return}
 if(page==='backup'){content.innerHTML=`<section class="panel"><h2>バックアップ</h2><div class="row"><button id="downloadBackup" class="primary">JSONを書き出す</button><label class="secondary">JSONを読み込む<input id="restoreBackup" type="file" accept="application/json" hidden></label></div></section>`;$('#downloadBackup').onclick=downloadBackup;$('#restoreBackup').onchange=restoreBackup;return}
 if(page==='trash'){const ts=state.tasks.filter(t=>t.deletedAt);content.innerHTML=`<div class="task-list">${ts.map(t=>`<article class="task"><span>♲</span><div><h3>${esc(t.title)}</h3></div><button class="secondary restore" data-id="${t.id}">戻す</button></article>`).join('')||'<div class="empty">ゴミ箱は空だよ</div>'}</div>`;document.querySelectorAll('.restore').forEach(b=>b.onclick=()=>{state.tasks.find(t=>t.id===b.dataset.id).deletedAt=null;dirty();render()});return}
 if(page==='archive'){const ts=state.tasks.filter(t=>t.archivedAt&&!t.deletedAt);content.innerHTML=`<div class="task-list">${ts.map(t=>`<article class="task"><span>▣</span><div><h3>${esc(t.title)}</h3></div><button class="secondary unarchive" data-id="${t.id}">元へ戻す</button></article>`).join('')||'<div class="empty">アーカイブはまだ空だよ</div>'}</div>`;document.querySelectorAll('.unarchive').forEach(b=>b.onclick=()=>{state.tasks.find(t=>t.id===b.dataset.id).archivedAt=null;dirty();render()});return}
 if(page==='notifications'){const rows=state.tasks.flatMap(t=>{const rs=t._mac?.reminders||[];if(t._mac?.reminderDate)rs.unshift({date:t._mac.reminderDate,recurrence:'once'});return rs.map(r=>({task:t,rule:r}))}).sort((a,b)=>String(a.rule.date).localeCompare(String(b.rule.date)));content.innerHTML=`<section class="panel"><h2>通知予定</h2>${rows.length>50?'<p class="warning">⚠ 通知予定が多いよ。不要な定期通知を整理してね。</p>':''}${rows.map(x=>`<div class="row spread"><span>${esc(x.task.title)}</span><small>${new Date(x.rule.date).toLocaleString('ja-JP')}・${esc(x.rule.recurrence||'once')}</small></div>`).join('')||'<p class="empty">通知予定はまだないよ</p>'}</section>`;return}
 if(page==='favorites'){state.favorites=state.favorites||[];content.innerHTML=`<section class="panel"><div class="row spread"><h2>よく使う仕事</h2><button id="newFavorite" class="primary">追加</button></div>${state.favorites.map(f=>`<div class="row spread favorite-row" data-id="${f.id}"><button class="secondary use-favorite">＋ ${esc(f.title)}</button><button class="danger delete-favorite">削除</button></div>`).join('')||'<p class="empty">よく使う仕事を登録しておけるよ</p>'}</section>`;$('#newFavorite').onclick=()=>{const title=prompt('仕事名');if(!title)return;state.favorites.unshift({id:uid(),title,category:'作業・雑務',status:'早め',note:''});dirty();renderUtility()};document.querySelectorAll('.favorite-row').forEach(r=>{const f=state.favorites.find(x=>x.id===r.dataset.id);r.querySelector('.use-favorite').onclick=()=>{state.tasks.unshift({id:uid(),title:f.title,category:f.category||'作業・雑務',status:f.status||'早め',minutes:f.minutes||null,note:f.note||'',date:today()});dirty();toast('今日の仕事へ追加したよ')};r.querySelector('.delete-favorite').onclick=()=>{state.favorites=state.favorites.filter(x=>x.id!==f.id);dirty();renderUtility()}});return}
 if(page==='display'){content.innerHTML=`<section class="panel"><h2>一覧表示</h2><label class="row"><input id="compactRows" type="checkbox" ${state.settings.compactRows?'checked':''}> コンパクト表示</label><label class="row"><input id="showDates" type="checkbox" ${state.settings.showDates!==false?'checked':''}> 作業日を表示</label><label class="row"><input id="showTimes" type="checkbox" ${state.settings.showTimes!==false?'checked':''}> 時間を表示</label></section>`;['compactRows','showDates','showTimes'].forEach(id=>$('#'+id).onchange=e=>{state.settings[id]=e.target.checked;dirty();render()});return}
 if(page==='legend'){content.innerHTML=`<section class="panel"><h2>進行状況</h2>${Object.values(statusInfo).map(s=>`<span class="pill">${esc(s[0])}</span>`).join(' ')}</section><section class="panel"><h2>ジャンル</h2>${categories().map(c=>`<p><span style="color:${categoryColor(c)}">●</span> ${esc(c)}</p>`).join('')}</section>`;return}
 if(page==='diagnostics'){const duplicate=[...new Set(state.tasks.filter((t,i,a)=>a.findIndex(x=>x.title===t.title)!==i).map(t=>t.title))],reminders=state.tasks.reduce((n,t)=>n+(t._mac?.reminders?.length||0)+(t._mac?.reminderDate?1:0),0);content.innerHTML=`<div class="summary"><div class="metric"><small>タスク</small><strong>${state.tasks.length}件</strong></div><div class="metric"><small>ゴミ箱</small><strong>${state.tasks.filter(t=>t.deletedAt).length}件</strong></div><div class="metric"><small>通知</small><strong>${reminders}件</strong></div></div><section class="panel"><h2>整合性</h2><p>重複タイトル：${duplicate.length}件</p>${duplicate.map(esc).map(x=>`<small>${x}</small>`).join('<br>')||'<p class="meta">問題なし</p>'}</section>`;return}
 content.innerHTML='<section class="panel"><h2>準備中</h2></section>'
}
const toLocalInput=v=>{if(!v)return'';const d=new Date(v);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
function openTaskV2(task=null,kind=null){
 const source=task?clone(task):{id:uid(),title:'',category:kind?'memo':'作業・雑務',status:kind==='idea'?'思いつき':kind==='memo'?'仕事メモ':'早め',date:today(),minutes:'',note:'',kind};
 const mac=source._mac||{}, links=mac.relatedLinks||source.relatedLinks||[], subtasks=mac.subtasks||source.subtasks||[], tags=mac.tags||source.tags||[];
 const f=$('#taskForm'), categoryOptions=[...new Set(['情マ','ママフリ','オシゴト','ママ本','とちポチ','印刷物','ジョブWEB','ウェブ','sns','伝ページ','イラスト','動画','照らし合わせ','作業・雑務','修正','その他','依頼中',...categories(),source.category].filter(Boolean))];
 f.innerHTML=`<h2>${task?'仕事内容を編集':'新しく追加'}</h2>
 <section class="detail-group"><h3>仕事内容</h3><div class="field"><label>仕事内容</label><input name="title" value="${esc(source.title)}" required autofocus></div><div class="field-grid"><div class="field"><label>ジャンル</label><select name="category">${categoryOptions.map(v=>`<option ${source.category===v?'selected':''}>${esc(v)}</option>`).join('')}</select></div><div class="field"><label>進行状況</label><select name="status">${['★絶対今日','早め','できればやる','いつかやる','毎日・定期','まち','一時保留','仕事メモ','思いつき','完了'].map(v=>`<option ${source.status===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field-grid"><div class="field"><label>時間（分）</label><input name="minutes" type="number" min="0" step="5" value="${esc(source.minutes||'')}"><div class="preset-row">${[5,10,15,20,30,45,60,90,120,180,300].map(v=>`<button type="button" class="time-preset" data-value="${v}">${v}</button>`).join('')}</div></div><div class="field"><label>作業日</label><input name="date" type="date" value="${esc(source.date||today())}"></div></div><div class="field"><label>タグ</label><input name="tags" value="${esc(tags.join(', '))}" placeholder="カンマ区切り"></div><div class="field"><label>メモ</label><textarea name="note">${esc(source.note||'')}</textarea></div><div class="switch-row"><label><input name="pinned" type="checkbox" ${source.pinned||mac.isPinned?'checked':''}> ピックアップに表示</label><label><input name="exclude" type="checkbox" ${source.excludeFromSheet||mac.excludeFromSheet?'checked':''}> アプリ専用（シートへ戻さない）</label></div></section>
 <section class="detail-group"><h3>情報</h3><div class="field"><label>画像</label>${source.image?`<img class="detail-preview" src="${source.image}" alt="添付画像">`:''}<input name="imageFile" type="file" accept="image/*"></div><div class="field"><label>フォルダパス</label><textarea name="folders" placeholder="1行に1つ">${esc((mac.folderPaths||source.folderPaths||[]).join('\n'))}</textarea></div><div class="field"><label>関連URL（タイトル｜URL）</label><textarea name="links" placeholder="参考サイト｜https://...">${esc(links.map(x=>`${x.title||''}｜${x.url||''}`).join('\n'))}</textarea></div><div class="field"><label>チェックリスト</label><textarea name="subtasks" placeholder="1行に1項目">${esc(subtasks.map(x=>`${x.isDone?'✓ ':''}${x.title}`).join('\n'))}</textarea></div></section>
 <section class="detail-group"><h3>通知・タスク管理</h3><div class="field-grid"><div class="field"><label>通知日時</label><input name="reminderDate" type="datetime-local" value="${toLocalInput(mac.reminderDate||source.reminderDate)}"></div><div class="field"><label>通知の繰り返し</label><select name="reminderRecurrence">${[['once','1回'],['daily','毎日'],['weekly','毎週'],['monthly','毎月']].map(([v,l])=>`<option value="${v}" ${(mac.reminders?.[0]?.recurrence||'once')===v?'selected':''}>${l}</option>`).join('')}</select></div></div><div class="field-grid"><div class="field"><label>定期タスク</label><select name="taskRecurrence">${[['none','なし'],['daily','毎日'],['weekly','毎週'],['monthly','毎月']].map(([v,l])=>`<option value="${v}" ${(mac.taskRecurrence||'none')===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>間隔</label><input name="recurrenceInterval" type="number" min="1" value="${mac.taskRecurrenceInterval||1}"></div></div></section>
 <section class="detail-group"><h3>その他</h3><div class="row"><button type="button" id="addFavorite" class="secondary">よく使う仕事へ追加</button>${task?'<button type="button" id="archiveTask" class="secondary">アーカイブ</button><button type="button" id="deleteTask" class="danger">削除</button>':''}</div></section>
 <menu><button value="cancel" class="secondary">変更せず戻す</button><button value="save" class="primary">変更を反映</button></menu>`;
 document.querySelectorAll('.time-preset').forEach(b=>b.onclick=()=>{f.elements.minutes.value=b.dataset.value});
 $('#addFavorite').onclick=()=>{state.favorites=state.favorites||[];state.favorites.unshift({id:uid(),title:f.elements.title.value,category:f.elements.category.value,status:f.elements.status.value,minutes:+f.elements.minutes.value||null,note:f.elements.note.value});dirty();toast('よく使う仕事へ追加したよ')};
 $('#archiveTask')?.addEventListener('click',()=>{const original=state.tasks.find(x=>x.id===source.id);if(original){original.archivedAt=new Date().toISOString();dirty();$('#taskDialog').close();render()}});
 $('#deleteTask')?.addEventListener('click',()=>{const original=state.tasks.find(x=>x.id===source.id);if(original){original.deletedAt=new Date().toISOString();dirty();$('#taskDialog').close();render()}});
 f.onsubmit=async e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const data=Object.fromEntries(new FormData(f));const relatedLinks=String(data.links||'').split(/\n/).map(v=>v.trim()).filter(Boolean).map(v=>{const p=v.split('｜');return{id:uid(),title:(p.shift()||'関連URL').trim(),url:p.join('｜').trim()}});const checklist=String(data.subtasks||'').split(/\n/).map(v=>v.trim()).filter(Boolean).map(v=>({id:uid(),title:v.replace(/^✓\s*/,''),isDone:/^✓/.test(v)}));const folderPaths=String(data.folders||'').split(/\n/).map(v=>v.trim()).filter(Boolean);const reminderDate=data.reminderDate?new Date(data.reminderDate).toISOString():null;Object.assign(source,{title:data.title,category:data.category,status:data.status,minutes:data.minutes?+data.minutes:null,date:data.date,note:data.note,tags:String(data.tags||'').split(',').map(v=>v.trim()).filter(Boolean),pinned:data.pinned==='on',excludeFromSheet:data.exclude==='on',relatedLinks,subtasks:checklist,folderPaths});source.kind=source.status==='思いつき'?'idea':source.status==='仕事メモ'?'memo':source.kind;source._mac={...mac,relatedLinks,subtasks:checklist,folderPaths,tags:source.tags,isPinned:source.pinned,excludeFromSheet:source.excludeFromSheet,reminderDate,reminders:reminderDate?[{id:mac.reminders?.[0]?.id||uid(),date:reminderDate,recurrence:data.reminderRecurrence,interval:1,weekday:2,ordinal:1}]:[],taskRecurrence:data.taskRecurrence,taskRecurrenceInterval:+data.recurrenceInterval||1};const file=f.elements.imageFile.files?.[0];if(file)source.image=await compressImage(file);const i=state.tasks.findIndex(x=>x.id===source.id);i<0?state.tasks.unshift(source):state.tasks[i]=source;dirty();$('#taskDialog').close();render()};
 $('#taskDialog').showModal();
}
const isoDate=d=>{if(!d)return null;const value=/T/.test(d)?d:`${d}T00:00:00`;return new Date(value).toISOString()};
const dayFromISO=d=>d?String(d).slice(0,10):'';
function taskToMac(t){return {...(t._mac||{}),id:t.id,category:t.category||'作業・雑務',title:t.title||'',minutes:t.minutes??null,timeLabel:t.timeLabel??null,status:t.done?'完了':(t.status||'早め'),isDone:!!t.done,taskDate:isoDate(t.date),createdAt:t.createdAt||new Date().toISOString(),note:t.note||'',isIdea:t.kind==='idea',isWorkMemo:t.kind==='memo',isPinned:!!t.pinned,startedAt:t.startedAt||null,completedAt:t.completedAt||null,archivedAt:t.archivedAt||null,excludeFromSheet:!!t.excludeFromSheet}}
function taskFromMac(t){return {...t._web,id:t.id||uid(),title:t.title||'',category:t.category||'作業・雑務',minutes:t.minutes??null,timeLabel:t.timeLabel??null,status:t.isDone?'完了':(t.status||'早め'),done:!!t.isDone,date:dayFromISO(t.taskDate||t.sheetBatchDate),note:t.note||'',kind:t.isIdea?'idea':t.isWorkMemo?'memo':null,pinned:!!t.isPinned,startedAt:t.startedAt||null,completedAt:t.completedAt||null,archivedAt:t.archivedAt||null,excludeFromSheet:!!t.excludeFromSheet,_mac:t}}
function stateToBackup(){const active=state.tasks.filter(t=>!t.deletedAt),deleted=state.tasks.filter(t=>t.deletedAt);return {tasks:active.map(taskToMac),categories:[...new Set(active.map(t=>t.category).filter(Boolean))],templates:state.favorites||[],trash:deleted.map(t=>({task:taskToMac(t),deletedAt:t.deletedAt})),workdays:(state.workdays||[]).map(w=>({...w,date:isoDate(w.date),clockIn:w.clockIn?isoDate(`${w.date}T${w.clockIn}:00`):null,clockOut:w.clockOut?isoDate(`${w.date}T${w.clockOut}:00`):null})),quickLaunchItems:[],favoriteLinks:(state.links||[]),imageMemos:[]}}
function backupToState(b){const incoming=(b.tasks||[]).map(taskFromMac);for(const d of b.trash||[]){const t=taskFromMac(d.task);t.deletedAt=d.deletedAt;incoming.push(t)}return {...clone(seed),...state,tasks:incoming,workdays:(b.workdays||[]).map(w=>({...w,date:dayFromISO(w.date),clockIn:w.clockIn?new Date(w.clockIn).toTimeString().slice(0,5):'',clockOut:w.clockOut?new Date(w.clockOut).toTimeString().slice(0,5):''})),links:b.favoriteLinks||state.links||[],favorites:b.templates||state.favorites||[]}}
function cloudEnvelope(){return {schemaVersion:2,updatedAt:new Date().toISOString(),deviceID,source:'web',backup:stateToBackup(),webState:state}}
function applyCloudPayload(payload){if(payload?.schemaVersion===2){state=payload.webState?{...clone(seed),...payload.webState}:backupToState(payload.backup||{})}else state={...clone(seed),...(payload||{})}}
async function ensureCloudClient(){if(cloudClient)return;const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');cloudClient=createClient(cloudConfig.url,cloudConfig.key);const {data}=await cloudClient.auth.getSession();cloudUser=data.session?.user||null}
async function connectCloud(){const status=$('#cloudStatus');try{cloudConfig={url:$('#cloudURL').value.trim(),key:$('#cloudKey').value.trim(),email:$('#cloudEmail').value.trim()};localStorage.setItem('kimu-cloud-config',JSON.stringify(cloudConfig));status.textContent='接続中…';cloudClient=null;await ensureCloudClient();const {data,error}=await cloudClient.auth.signInWithPassword({email:cloudConfig.email,password:$('#cloudPassword').value});if(error)throw error;cloudUser=data.user;toast('Supabaseへ接続したよ');await pullCloudState(true);renderUtility()}catch(e){status.textContent='接続できなかったよ：'+e.message}}
async function pushCloudState(silent=false){if(!cloudClient||!cloudUser||cloudBusy)return;cloudBusy=true;const status=$('#cloudStatus');if(status)status.textContent='保存中…';const now=new Date().toISOString();const {error}=await cloudClient.from('kimu_snapshots').upsert({user_id:cloudUser.id,payload:cloudEnvelope(),client_updated_at:now},{onConflict:'user_id'});cloudBusy=false;if(error){if(status)status.textContent='保存できなかったよ：'+error.message;return}localStorage.setItem('kimu-last-cloud-sync',now);localStorage.setItem('kimu-local-updated-at',now);$('#saveState').textContent='● クラウド同期済み';if(status)status.textContent='クラウド同期済み：'+new Date(now).toLocaleString('ja-JP');if(!silent)toast('クラウドへ保存したよ')}
async function pullCloudState(silent=false){if(!cloudClient||!cloudUser||cloudBusy)return;cloudBusy=true;const status=$('#cloudStatus');if(status)status.textContent='読込中…';const {data,error}=await cloudClient.from('kimu_snapshots').select('payload,client_updated_at').eq('user_id',cloudUser.id).maybeSingle();cloudBusy=false;if(error){if(status)status.textContent='読み込めなかったよ：'+error.message;return}if(!data){if(status)status.textContent='クラウドにはまだデータがないよ';await pushCloudState(true);return}const last=localStorage.getItem('kimu-last-cloud-sync')||'',local=localStorage.getItem('kimu-local-updated-at')||'',remote=data.client_updated_at||data.payload?.updatedAt||'';if(last&&local>last&&remote>last&&!silent){if(!confirm('この端末とクラウドの両方に変更があるよ。クラウドの内容を優先して読み込む？'))return}if(!last&&state.tasks.length&&remote&&!silent){if(!confirm('この端末の内容をクラウドの内容で置き換える？'))return}cloudApplying=true;applyCloudPayload(data.payload);save();cloudApplying=false;localStorage.setItem('kimu-last-cloud-sync',remote);localStorage.setItem('kimu-local-updated-at',remote);$('#saveState').textContent='● クラウド同期済み';render();if(!silent)toast('クラウドから読み込んだよ')}
async function resumeCloud(){try{await ensureCloudClient();if(cloudUser)await pullCloudState(true)}catch(e){console.warn('auto sync',e)}}
function openImport(mode='import'){const f=$('#importForm');f.innerHTML=`<h2>${mode==='import'?'スプレッドシートから取り込み':'スプレッドシートへ戻す'}</h2><textarea id="sheetText" placeholder="▼▼ 7/1（水）▼▼\nジャンル　仕事内容　時間　進行状況">${mode==='export'?esc(exportTSV()):''}</textarea><menu><button value="cancel" class="secondary">閉じる</button><button type="button" id="sheetAction" class="primary">${mode==='import'?'取り込む':'コピー'}</button></menu>`;$('#sheetAction').onclick=()=>{mode==='import'?importTSV($('#sheetText').value):copyText($('#sheetText').value,'シート用データをコピーしたよ');if(mode==='import')$('#importDialog').close()};$('#importDialog').showModal()}
function importTSV(text){const first=text.split(/\r?\n/).find(Boolean)||'',m=first.match(/(\d{1,2})\/(\d{1,2})/);if(!m)return toast('先頭の日付が見つからないよ');const y=new Date().getFullYear(),date=`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;const rows=text.split(/\r?\n/).slice(1);rows.forEach(line=>{const c=line.split('\t');if(!c[1]||c.join('').includes('仕事内容'))return;const old=state.tasks.find(t=>t.date===date&&t.title===c[1]);const item=old||{id:uid(),date};Object.assign(item,{category:c[0]||'memo',title:c[1],minutes:+c[2]||null,status:c[3]||'未設定',done:(c[3]||'').includes('完了')});if(!old)state.tasks.push(item)});dirty();render();toast('取り込んだよ')}
function exportTSV(){const d=today(),[y,m,day]=d.split('-');const rows=state.tasks.filter(t=>t.date===d&&!t.deletedAt&&!t.excludeFromSheet).map(t=>[t.category,t.title,t.minutes||'',t.done?'完了':t.status].join('\t'));return [`▼▼ ${+m}/${+day} ▼▼`,...rows].join('\n')}
function downloadBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`kimu-task-${today()}.json`;a.click()}
function restoreBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('復元したよ')}catch{toast('読み込めなかったよ')}};r.readAsText(f)}
function copyText(v,msg){navigator.clipboard.writeText(v).then(()=>toast(msg))}
function toast(v){const t=$('#toast');t.textContent=v;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('open')}
$('#menuButton').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('open')};$('#closeSidebar').onclick=closeSidebar;$('#scrim').onclick=closeSidebar;$('#addButton').onclick=()=>openTask(null,page==='idea'?'idea':page==='memo'?'memo':null);$('#importButton').onclick=()=>openImport('import');$('#exportButton').onclick=()=>openImport('export');
function openTaskDetail(task){
 const mac=task._mac||{}, links=mac.relatedLinks||task.relatedLinks||[], subtasks=mac.subtasks||task.subtasks||[], folders=mac.folderPaths||task.folderPaths||[], tags=mac.tags||task.tags||[], reminder=mac.reminderDate||task.reminderDate||mac.reminders?.[0]?.date;
 const f=$('#taskForm');f.innerHTML=`<div class="detail-head"><div><span class="pill" style="color:${categoryColor(task.category||'memo')}">${esc(task.category||'memo')}</span><span class="pill">${esc(task.status||'未設定')}</span><h2>${esc(task.title)}</h2></div><button value="cancel" class="icon" aria-label="閉じる">×</button></div>
 <section class="detail-group detail-read"><h3>仕事内容</h3><dl><dt>時間</dt><dd>${task.minutes?`${task.minutes}分`:'未設定'}</dd><dt>作業日</dt><dd>${esc(task.date||'未設定')}</dd>${tags.length?`<dt>タグ</dt><dd>${tags.map(t=>`<span class="pill">${esc(t)}</span>`).join(' ')}</dd>`:''}<dt>メモ</dt><dd class="prewrap">${esc(task.note||'—')}</dd></dl></section>
 <section class="detail-group detail-read"><h3>情報</h3>${task.image?`<img class="detail-view-image" src="${task.image}" alt="添付画像">`:''}${folders.length?`<h4>フォルダ</h4>${folders.map(v=>`<p class="path-text">${esc(v)}</p>`).join('')}`:''}${links.length?`<h4>関連URL</h4>${links.map(v=>`<p><a href="${esc(v.url)}" target="_blank" rel="noopener">${esc(v.title||v.url)}</a></p>`).join('')}`:''}${subtasks.length?`<h4>チェックリスト</h4>${subtasks.map(v=>`<p>${v.isDone?'☑':'☐'} ${esc(v.title)}</p>`).join('')}`:''}${!task.image&&!folders.length&&!links.length&&!subtasks.length?'<p class="meta">登録情報はまだないよ</p>':''}</section>
 <section class="detail-group detail-read"><h3>通知・タスク管理</h3><dl><dt>通知</dt><dd>${reminder?new Date(reminder).toLocaleString('ja-JP'):'なし'}</dd><dt>定期タスク</dt><dd>${esc(mac.taskRecurrence&&mac.taskRecurrence!=='none'?mac.taskRecurrence:'なし')}</dd></dl></section>
 <section class="detail-actions"><button type="button" id="detailStart" class="secondary">${task.startedAt?'作業中':'今から開始'}</button><button type="button" id="detailDone" class="secondary">${task.done?'未完了へ戻す':'完了'}</button><button type="button" id="detailEdit" class="primary">編集</button></section>`;
 $('#detailStart').onclick=()=>{const original=state.tasks.find(x=>x.id===task.id);original.startedAt=original.startedAt?null:new Date().toISOString();dirty();$('#taskDialog').close();render();toast(original.startedAt?'作業を開始したよ':'作業中を解除したよ')};
 $('#detailDone').onclick=()=>{const original=state.tasks.find(x=>x.id===task.id);original.done=!original.done;original.completedAt=original.done?new Date().toISOString():null;dirty();$('#taskDialog').close();render();toast(original.done?'完了にしたよ':'未完了へ戻したよ')};
 $('#detailEdit').onclick=()=>{const current=state.tasks.find(x=>x.id===task.id);$('#taskDialog').close();openTaskV2(current)};
 $('#taskDialog').showModal();
}
function openTaskRouter(task=null,kind=null){task?openTaskDetail(task):openTaskV2(null,kind)}
openTask=openTaskRouter;renderUtility=renderUtilityV2;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();resumeCloud();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')resumeCloud()});
window.addEventListener('online',resumeCloud);
