const KEY='kimu-task-web-v1';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const seed={tasks:[],workdays:[],links:[],imageMemos:[],settings:{endTime:'19:00',shareURL:'https://x.gd/hrRag',includeURL:false},groups:{schedule:true,progress:true,genre:false,settings:false}};
let state=load(), page='today';
let cloudClient=null, cloudUser=null;
let cloudApplying=false, cloudBusy=false;
const cloudDefaults={url:'https://qlepvmxyinathcicesfv.supabase.co',key:'sb_publishable_PkdyTEB-pvuchkJqm3f7Pw_8GGJK4Au'};
let cloudConfig={...cloudDefaults,...JSON.parse(localStorage.getItem('kimu-cloud-config')||'{}')};
const deviceID=localStorage.getItem('kimu-device-id')||uid();
localStorage.setItem('kimu-device-id',deviceID);
const $=s=>document.querySelector(s), content=$('#content');
function load(){try{return {...structuredClone(seed),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent=cloudUser?'● 端末に保存・同期待ち':'● 保存済み'}
function dirty(){
 localStorage.setItem('kimu-local-updated-at',new Date().toISOString());
 $('#saveState').textContent='○ 保存中';clearTimeout(dirty.t);dirty.t=setTimeout(()=>{save();scheduleCloudPush()},180)
}
function scheduleCloudPush(){if(!cloudUser||cloudApplying)return;clearTimeout(scheduleCloudPush.t);scheduleCloudPush.t=setTimeout(()=>pushCloudState(true),1400)}
const statusInfo={urgent:['★絶対今日','絶対今日'],early:['早め','早め'],mid:['できればやる','中期'],long:['いつかやる','長期'],wait:['まち','まち'],hold:['一時保留','一時保留'],done:['完了','完了']};
const navGroups=[
 {id:'memo',title:'メモ',fixed:true,items:[['idea','💡','思いつきBOX','idea'],['memo','📝','仕事メモ','memo'],['imageMemo','🖼','画像メモ','image'],['links','🔗','よく使うリンク集']]},
 {id:'schedule',title:'予定管理',items:[['working','▶','いま作業中'],['timeline','◷','タイムライン'],['calendar','▣','カレンダー'],['notifications','🔔','通知一覧'],['attendance','◉','出退勤管理'],['review','▥','今日の振り返り'],['tomorrow','☀','明日の予定'],['line','💬','LINE用 今日の仕事']]},
 {id:'progress',title:'進行状況',items:[['all','☷','すべて'],['today','☀','今日'],['mid','▣','中期'],['long','◴','長期'],['wait','Ⅱ','まち'],['done','✓','完了'],['hold','□','一時保留']]},
 {id:'genre',title:'ジャンル',items:[['genres','▤','すべて']]},
 {id:'settings',title:'設定',items:[['favorites','☆','よく使う仕事'],['sync','↻','同期設定'],['backup','⇩','バックアップ'],['trash','♲','ゴミ箱']]}
];
function renderNav(){
 $('#nav').innerHTML=`<div class="nav-top"><button class="nav-item ${page==='pickup'?'active':''}" data-page="pickup">⭐ ピックアップ</button></div>`+navGroups.map(g=>`<section class="nav-group ${!g.fixed&&!state.groups[g.id]?'closed':''}" data-group="${g.id}"><button class="group-toggle">${g.title}</button><div class="nav-children">${g.items.map(i=>`<div class="nav-row"><button class="nav-item ${page===i[0]?'active':''}" data-page="${i[0]}"><span>${i[1]}</span>${i[2]}</button>${i[3]?`<button class="quick-add" data-quick="${i[3]}" aria-label="${i[2]}へ追加">＋</button>`:''}</div>`).join('')}${g.id==='genre'?categories().map(c=>`<button class="nav-item ${page==='cat:'+c?'active':''}" data-page="cat:${esc(c)}"><span style="color:${categoryColor(c)}">●</span>${esc(c)}</button>`).join(''):''}</div></section>`).join('');
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;closeSidebar();render()});
 document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.dataset.quick==='image'){page='imageMemo';closeSidebar();render();setTimeout(()=>$('#imageFile')?.click(),0)}else openTask(null,b.dataset.quick)});
 document.querySelectorAll('.group-toggle').forEach(b=>b.onclick=()=>{const g=b.closest('.nav-group'),id=g.dataset.group;if(id==='memo')return;state.groups[id]=!state.groups[id];dirty();renderNav()});
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=()=>[...new Set(state.tasks.map(t=>t.category).filter(Boolean))];
const categoryColor=s=>`hsl(${[...s].reduce((a,c)=>a+c.charCodeAt(0),0)%360} 55% 48%)`;
const isDate=(t,d)=>t.date===d;
function activeTasks(){return state.tasks.filter(t=>!t.done&&!t.deletedAt)}
function tasksForPage(){let a=activeTasks(); if(page==='idea')return a.filter(t=>t.kind==='idea');if(page==='memo')return a.filter(t=>t.kind==='memo');a=a.filter(t=>!t.kind);if(page==='today')return a.filter(t=>['★絶対今日','早め'].includes(t.status)&&isDate(t,today()));if(page==='mid')return a.filter(t=>t.status==='できればやる');if(page==='long')return a.filter(t=>t.status==='いつかやる');if(page==='wait')return a.filter(t=>t.status==='まち');if(page==='hold')return a.filter(t=>t.status==='一時保留');if(page==='done')return state.tasks.filter(t=>t.done&&!t.deletedAt);if(page==='tomorrow'){const d=new Date();d.setDate(d.getDate()+1);return a.filter(t=>isDate(t,d.toISOString().slice(0,10)))}if(page.startsWith('cat:'))return a.filter(t=>t.category===page.slice(4));if(page==='working')return a.filter(t=>t.startedAt);if(page==='pickup')return a.filter(t=>t.pinned||t.reminder);return a}
function render(){renderNav();const titles={pickup:'ピックアップ',idea:'思いつきBOX',memo:'仕事メモ',imageMemo:'画像メモ',links:'よく使うリンク集',all:'進行状況：すべて',today:'今日',mid:'中期',long:'長期',wait:'まち',hold:'一時保留',done:'完了',working:'いま作業中',timeline:'タイムライン',calendar:'カレンダー',notifications:'通知一覧',attendance:'出退勤管理',review:'今日の振り返り',tomorrow:'明日の予定',line:'LINE用 今日の仕事',genres:'ジャンル：すべて',favorites:'よく使う仕事',sync:'同期設定',backup:'バックアップ',trash:'ゴミ箱'};$('#pageTitle').textContent=page.startsWith('cat:')?page.slice(4):(titles[page]||'Kimu Task');$('#pageSub').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
 if(page==='attendance')return renderAttendance();if(page==='line')return renderLine();if(page==='imageMemo')return renderImageMemos();if(page==='links')return renderLinks();if(page==='review')return renderReview();if(page==='calendar')return renderCalendar();if(page==='timeline')return renderTimeline();if(page==='backup'||page==='sync'||page==='favorites'||page==='notifications'||page==='trash')return renderUtility();renderTasks();}
function renderTasks(){const tasks=tasksForPage();const doneToday=state.tasks.filter(t=>t.done&&t.completedAt?.startsWith(today())).length;content.innerHTML=`<div class="summary"><div class="metric"><small>表示中</small><strong>${tasks.length}件</strong></div><div class="metric"><small>予定時間</small><strong>${tasks.reduce((a,t)=>a+(+t.minutes||0),0)}分</strong></div><div class="metric"><small>今日の完了</small><strong>${doneToday}件</strong></div></div><div class="task-list">${tasks.length?tasks.map(taskRow).join(''):'<div class="empty">ここにはまだ何もないよ</div>'}</div>`;bindTaskEvents()}
function taskRow(t){const cls=t.status==='★絶対今日'?'urgent':t.status==='早め'?'early':t.status==='できればやる'?'mid':'';return `<article class="task" data-id="${t.id}"><button class="check ${t.done?'done':''}" aria-label="完了">${t.done?'✓':''}</button><div class="task-main">${t.image?`<img class="task-thumb" src="${t.image}" alt="">`:''}<h3>${esc(t.title)}</h3><div class="meta"><span class="pill" style="color:${categoryColor(t.category||'memo')}">${esc(t.category||'memo')}</span><span class="pill ${cls}">${esc(t.status||'未設定')}</span><span>${esc(t.date||'')}</span></div></div><span class="time">${t.minutes?`${t.minutes}分`:''}</span></article>`}
function bindTaskEvents(){document.querySelectorAll('.task').forEach(r=>{r.querySelector('.check').onclick=e=>{e.stopPropagation();const t=state.tasks.find(x=>x.id===r.dataset.id);t.done=!t.done;t.completedAt=t.done?new Date().toISOString():null;dirty();render()};r.onclick=()=>openTask(state.tasks.find(x=>x.id===r.dataset.id))})}
function openTask(task=null,kind=null){const t=task?{...task}:{id:uid(),title:'',category:kind?'memo':'作業・雑務',status:kind==='idea'?'思いつき':kind==='memo'?'仕事メモ':'早め',date:today(),minutes:'',note:'',kind};const f=$('#taskForm');f.innerHTML=`<h2>${task?'仕事内容を編集':'新しく追加'}</h2><div class="field"><label>仕事内容</label><input name="title" value="${esc(t.title)}" required autofocus></div><div class="field"><label>ジャンル</label><input name="category" value="${esc(t.category||'')}"></div><div class="field"><label>進行状況</label><select name="status">${['★絶対今日','早め','できればやる','いつかやる','毎日・定期','まち','一時保留','仕事メモ','思いつき'].map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>時間（分）</label><input name="minutes" type="number" step="5" value="${esc(t.minutes||'')}"></div><div class="field"><label>作業日</label><input name="date" type="date" value="${esc(t.date||today())}"></div><div class="field"><label>メモ</label><textarea name="note">${esc(t.note||'')}</textarea></div><menu>${task?'<button type="button" class="danger" id="deleteTask">削除</button>':''}<button value="cancel" class="secondary">戻る</button><button value="save" class="primary">保存</button></menu>`;f.onsubmit=e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const data=Object.fromEntries(new FormData(f));Object.assign(t,data,{minutes:data.minutes?+data.minutes:null});const i=state.tasks.findIndex(x=>x.id===t.id);i<0?state.tasks.unshift(t):state.tasks[i]=t;dirty();$('#taskDialog').close();render()};$('#deleteTask')?.addEventListener('click',()=>{const i=state.tasks.findIndex(x=>x.id===t.id);state.tasks[i].deletedAt=new Date().toISOString();dirty();$('#taskDialog').close();render()});$('#taskDialog').showModal()}
function renderAttendance(){let w=state.workdays.find(x=>x.date===today())||{id:uid(),date:today(),clockIn:'',clockOut:'',breakMinutes:120,note:''};const histories=[...state.workdays].sort((a,b)=>b.date.localeCompare(a.date));content.innerHTML=`<div class="attendance-grid"><section class="panel"><h2>今日の出退勤</h2><div class="row"><button class="primary" id="clockIn">出勤</button><button class="primary" id="clockOut">退勤</button></div><div class="field"><label>出勤時刻</label><input id="inTime" type="time" value="${w.clockIn||''}"></div><div class="field"><label>退勤時刻</label><input id="outTime" type="time" value="${w.clockOut||''}"></div><div class="field"><label>休憩合計</label><input id="breakMinutes" type="number" step="5" value="${w.breakMinutes}"></div><div class="field"><label>勤務メモ</label><textarea id="workNote">${esc(w.note)}</textarea></div><p class="meta">基本休憩：10:30〜10:45 / 12:00〜13:15 / 15:00〜15:15 / 17:00〜17:15</p></section><section class="panel"><h2>日別履歴</h2>${histories.length?histories.map(x=>`<div class="row spread" style="padding:9px 0;border-bottom:1px solid var(--line)"><span>${x.date}</span><strong>${x.clockIn||'--:--'}〜${x.clockOut||'勤務中'}</strong><button class="secondary copy-work" data-in="${x.clockIn||''}" data-out="${x.clockOut||''}">2セルコピー</button></div>`).join(''):'<p class="empty">履歴はまだないよ</p>'}</section></div>`;const up=()=>{w.clockIn=$('#inTime').value;w.clockOut=$('#outTime').value;w.breakMinutes=+$('#breakMinutes').value;w.note=$('#workNote').value;const i=state.workdays.findIndex(x=>x.date===today());i<0?state.workdays.push(w):state.workdays[i]=w;dirty()};$('#clockIn').onclick=()=>{$('#inTime').value=new Date().toTimeString().slice(0,5);up();renderAttendance()};$('#clockOut').onclick=()=>{$('#outTime').value=new Date().toTimeString().slice(0,5);up();renderAttendance()};['inTime','outTime','breakMinutes','workNote'].forEach(id=>$('#'+id).onchange=up);document.querySelectorAll('.copy-work').forEach(b=>b.onclick=()=>copyText(`${b.dataset.in}\t${b.dataset.out}`,'2セル用にコピーしたよ'))}
function renderLine(){const s=state.settings;content.innerHTML=`<section class="panel"><div class="row spread"><h2>LINE用 今日の仕事</h2><button class="primary" id="copyLine">コピー</button></div><div class="row"><label>終了時間 <input id="endTime" type="time" value="${s.endTime}"></label><label><input id="includeURL" type="checkbox" ${s.includeURL?'checked':''}> リンクを付ける</label><input id="shareURL" value="${esc(s.shareURL)}" style="flex:1" ${s.includeURL?'':'disabled'}></div><textarea id="lineOutput" class="editor line-output">${esc(makeLine())}</textarea></section>`;const refresh=()=>{s.endTime=$('#endTime').value;s.includeURL=$('#includeURL').checked;s.shareURL=$('#shareURL').value;$('#shareURL').disabled=!s.includeURL;$('#lineOutput').value=makeLine();dirty()};['endTime','includeURL','shareURL'].forEach(id=>$('#'+id).onchange=refresh);$('#copyLine').onclick=()=>copyText($('#lineOutput').value,'LINE用文面をコピーしたよ')}
function renderImageMemos(){state.imageMemos=state.imageMemos||[];content.innerHTML=`<section class="panel"><h2>画像をメモ</h2><div class="image-form"><label class="image-picker">📷 写真を選ぶ／撮る<input id="imageFile" type="file" accept="image/*" capture="environment" hidden></label><input id="imageTitle" placeholder="タイトル（あとからでもOK）"><textarea id="imageNote" placeholder="メモ"></textarea><button id="saveImageMemo" class="primary" disabled>画像メモへ追加</button></div><p class="meta">端末内保存では容量を抑えるため画像を自動で縮小するよ。</p></section><section class="image-grid">${state.imageMemos.map(m=>`<article class="image-card" data-id="${m.id}"><img src="${m.image}" alt=""><div><strong>${esc(m.title||'画像メモ')}</strong><p>${esc(m.note||'')}</p><small>${new Date(m.createdAt).toLocaleString('ja-JP')}</small></div><div class="row"><button class="primary move-idea">思いつきBOXへ</button><button class="danger delete-image">削除</button></div></article>`).join('')||'<div class="panel empty">写真やスクリーンショットを、忘れる前に置いておけるよ</div>'}</section>`;let pendingImage='';$('#imageFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;pendingImage=await compressImage(file);$('#saveImageMemo').disabled=false;toast('画像を準備したよ')};$('#saveImageMemo').onclick=()=>{if(!pendingImage)return;state.imageMemos.unshift({id:uid(),image:pendingImage,title:$('#imageTitle').value.trim(),note:$('#imageNote').value.trim(),createdAt:new Date().toISOString()});dirty();renderImageMemos()};document.querySelectorAll('.image-card').forEach(card=>{const memo=state.imageMemos.find(m=>m.id===card.dataset.id);card.querySelector('.move-idea').onclick=()=>{state.tasks.unshift({id:uid(),title:memo.title||'画像メモ',category:'memo',status:'思いつき',date:today(),note:memo.note||'',kind:'idea',image:memo.image});state.imageMemos=state.imageMemos.filter(m=>m.id!==memo.id);dirty();renderImageMemos();toast('思いつきBOXへ移動したよ')};card.querySelector('.delete-image').onclick=()=>{state.imageMemos=state.imageMemos.filter(m=>m.id!==memo.id);dirty();renderImageMemos()}})}
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}
function renderLinks(){state.links=state.links||[];content.innerHTML=`<section class="panel"><h2>リンクを追加</h2><div class="link-form"><input id="linkTitle" placeholder="タイトル（例：元スプレッド）"><input id="linkURL" type="url" placeholder="https://"><button id="addLink" class="primary">追加</button></div></section><section class="link-grid">${state.links.map(l=>`<article class="link-card" data-id="${l.id}"><a href="${esc(l.url)}" target="_blank" rel="noopener"><span>🔗</span><div><strong>${esc(l.title)}</strong><small>${esc(l.url)}</small></div></a><div class="row"><button class="secondary edit-link">編集</button><button class="danger delete-link">削除</button></div></article>`).join('')||'<div class="panel empty">よく使うページを登録しておくと、ここからすぐ開けるよ</div>'}</section>`;$('#addLink').onclick=()=>{const title=$('#linkTitle').value.trim(),url=$('#linkURL').value.trim();if(!title||!url)return toast('タイトルとURLを入力してね');state.links.push({id:uid(),title,url});dirty();renderLinks()};document.querySelectorAll('.link-card').forEach(card=>{const link=state.links.find(l=>l.id===card.dataset.id);card.querySelector('.edit-link').onclick=()=>{const title=prompt('タイトル',link.title);if(title===null)return;const url=prompt('URL',link.url);if(url===null)return;link.title=title.trim();link.url=url.trim();dirty();renderLinks()};card.querySelector('.delete-link').onclick=()=>{state.links=state.links.filter(l=>l.id!==link.id);dirty();renderLinks()}})}
function makeLine(){const group=(h,s)=>`【${h}】\n${activeTasks().filter(t=>t.date===today()&&t.status===s).map(t=>'●'+t.title).join('\n')||'（なし）'}`;let out=[group('絶対今日','★絶対今日'),group('早め','早め'),group('今日やりたいこと','できればやる'),`（${state.settings.endTime}）`];if(state.settings.includeURL&&state.settings.shareURL)out.push(state.settings.shareURL);return out.join('\n\n')}
function renderReview(){const done=state.tasks.filter(t=>t.done&&t.completedAt?.startsWith(today())),remain=activeTasks().filter(t=>t.date===today());content.innerHTML=`<div class="summary"><div class="metric"><small>完了</small><strong>${done.length}件</strong></div><div class="metric"><small>完了時間</small><strong>${done.reduce((a,t)=>a+(+t.minutes||0),0)}分</strong></div><div class="metric"><small>残り</small><strong>${remain.length}件</strong></div></div><section class="panel"><h2>完了した仕事</h2>${done.map(t=>`<p>✓ ${esc(t.title)}</p>`).join('')||'<p class="meta">まだないよ</p>'}</section><section class="panel"><h2>残った仕事</h2>${remain.map(t=>`<p>• ${esc(t.title)}</p>`).join('')||'<p class="meta">なし</p>'}</section>`}
function renderCalendar(){const ds=[...new Set(state.tasks.map(t=>t.date).filter(Boolean))].sort();content.innerHTML=`<section class="panel"><h2>日付ごとの予定</h2>${ds.map(d=>`<h3>${d}</h3>${state.tasks.filter(t=>t.date===d&&!t.deletedAt).map(t=>`<p>${t.done?'✓':'○'} ${esc(t.title)}</p>`).join('')}`).join('')||'<p class="empty">予定はまだないよ</p>'}</section>`}
function renderTimeline(){const ts=activeTasks().filter(t=>t.date===today()).sort((a,b)=>(a.order||0)-(b.order||0));let cursor=new Date(),rows=ts.map(t=>{const start=cursor.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});cursor=new Date(cursor.getTime()+(+t.minutes||15)*60000);return `<div class="task"><span class="time">${start}</span><div><h3>${esc(t.title)}</h3><div class="meta">${t.minutes||15}分</div></div></div>`}).join('');content.innerHTML=`<section class="panel"><h2>現在からの予定</h2><div class="task-list">${rows||'<div class="empty">今日の仕事を登録してね</div>'}</div></section>`}
function renderUtility(){if(page==='sync'){const last=localStorage.getItem('kimu-last-cloud-sync');content.innerHTML=`<section class="panel"><h2>Supabase自動同期</h2><p>${cloudUser?`接続中：${esc(cloudUser.email||'ログイン済み')}`:'Mac・iPhone・Webで同じ内容を使うための接続設定だよ。'}</p><div class="field"><label>Project URL</label><input id="cloudURL" value="${esc(cloudConfig.url||'')}" placeholder="https://xxxx.supabase.co"></div><div class="field"><label>Publishable key</label><input id="cloudKey" value="${esc(cloudConfig.key||'')}" placeholder="sb_publishable_... / anon key"></div><div class="field"><label>メール</label><input id="cloudEmail" type="email" value="${esc(cloudConfig.email||'')}"></div><div class="field"><label>パスワード</label><input id="cloudPassword" type="password" autocomplete="current-password"></div><div class="row"><button id="connectCloud" class="primary">${cloudUser?'再接続':'接続'}</button><button id="pushCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ保存</button><button id="pullCloud" class="secondary" ${cloudUser?'':'disabled'}>今すぐ読込</button></div><p id="cloudStatus" class="meta">${last?'最終同期：'+new Date(last).toLocaleString('ja-JP'):'接続後は起動時に読込、変更後に自動保存するよ。'} パスワードは保存しないよ。</p></section>`;$('#connectCloud').onclick=connectCloud;$('#pushCloud').onclick=()=>pushCloudState(false);$('#pullCloud').onclick=()=>pullCloudState(false)}else if(page==='backup'){content.innerHTML=`<section class="panel"><h2>バックアップ</h2><div class="row"><button id="downloadBackup" class="primary">JSONを書き出す</button><label class="secondary">JSONを読み込む<input id="restoreBackup" type="file" accept="application/json" hidden></label></div></section>`;$('#downloadBackup').onclick=downloadBackup;$('#restoreBackup').onchange=restoreBackup}else if(page==='trash'){const ts=state.tasks.filter(t=>t.deletedAt);content.innerHTML=`<div class="task-list">${ts.map(t=>`<article class="task"><span>♲</span><div><h3>${esc(t.title)}</h3></div><button class="secondary restore" data-id="${t.id}">戻す</button></article>`).join('')||'<div class="empty">ゴミ箱は空だよ</div>'}</div>`;document.querySelectorAll('.restore').forEach(b=>b.onclick=()=>{state.tasks.find(t=>t.id===b.dataset.id).deletedAt=null;dirty();render()})}else content.innerHTML='<section class="panel"><h2>準備中</h2><p>Mac版とつながる形で順番に追加していくよ。</p></section>'}
const isoDate=d=>{if(!d)return null;const value=/T/.test(d)?d:`${d}T00:00:00`;return new Date(value).toISOString()};
const dayFromISO=d=>d?String(d).slice(0,10):'';
function taskToMac(t){return {...(t._mac||{}),id:t.id,category:t.category||'作業・雑務',title:t.title||'',minutes:t.minutes??null,timeLabel:t.timeLabel??null,status:t.done?'完了':(t.status||'早め'),isDone:!!t.done,taskDate:isoDate(t.date),createdAt:t.createdAt||new Date().toISOString(),note:t.note||'',isIdea:t.kind==='idea',isWorkMemo:t.kind==='memo',isPinned:!!t.pinned,startedAt:t.startedAt||null,completedAt:t.completedAt||null,excludeFromSheet:!!t.excludeFromSheet}}
function taskFromMac(t){return {...t._web,id:t.id||uid(),title:t.title||'',category:t.category||'作業・雑務',minutes:t.minutes??null,timeLabel:t.timeLabel??null,status:t.isDone?'完了':(t.status||'早め'),done:!!t.isDone,date:dayFromISO(t.taskDate||t.sheetBatchDate),note:t.note||'',kind:t.isIdea?'idea':t.isWorkMemo?'memo':null,pinned:!!t.isPinned,startedAt:t.startedAt||null,completedAt:t.completedAt||null,excludeFromSheet:!!t.excludeFromSheet,_mac:t}}
function stateToBackup(){const active=state.tasks.filter(t=>!t.deletedAt),deleted=state.tasks.filter(t=>t.deletedAt);return {tasks:active.map(taskToMac),categories:[...new Set(active.map(t=>t.category).filter(Boolean))],templates:[],trash:deleted.map(t=>({task:taskToMac(t),deletedAt:t.deletedAt})),workdays:(state.workdays||[]).map(w=>({...w,date:isoDate(w.date),clockIn:w.clockIn?isoDate(`${w.date}T${w.clockIn}:00`):null,clockOut:w.clockOut?isoDate(`${w.date}T${w.clockOut}:00`):null})),quickLaunchItems:[],favoriteLinks:(state.links||[]),imageMemos:[]}}
function backupToState(b){const incoming=(b.tasks||[]).map(taskFromMac);for(const d of b.trash||[]){const t=taskFromMac(d.task);t.deletedAt=d.deletedAt;incoming.push(t)}return {...structuredClone(seed),...state,tasks:incoming,workdays:(b.workdays||[]).map(w=>({...w,date:dayFromISO(w.date),clockIn:w.clockIn?new Date(w.clockIn).toTimeString().slice(0,5):'',clockOut:w.clockOut?new Date(w.clockOut).toTimeString().slice(0,5):''})),links:b.favoriteLinks||state.links||[]}}
function cloudEnvelope(){return {schemaVersion:2,updatedAt:new Date().toISOString(),deviceID,source:'web',backup:stateToBackup(),webState:state}}
function applyCloudPayload(payload){if(payload?.schemaVersion===2){state=payload.webState?{...structuredClone(seed),...payload.webState}:backupToState(payload.backup||{})}else state={...structuredClone(seed),...(payload||{})}}
async function ensureCloudClient(){if(cloudClient)return;const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');cloudClient=createClient(cloudConfig.url,cloudConfig.key);const {data}=await cloudClient.auth.getSession();cloudUser=data.session?.user||null}
async function connectCloud(){const status=$('#cloudStatus');try{cloudConfig={url:$('#cloudURL').value.trim(),key:$('#cloudKey').value.trim(),email:$('#cloudEmail').value.trim()};localStorage.setItem('kimu-cloud-config',JSON.stringify(cloudConfig));status.textContent='接続中…';cloudClient=null;await ensureCloudClient();const {data,error}=await cloudClient.auth.signInWithPassword({email:cloudConfig.email,password:$('#cloudPassword').value});if(error)throw error;cloudUser=data.user;toast('Supabaseへ接続したよ');await pullCloudState(true);renderUtility()}catch(e){status.textContent='接続できなかったよ：'+e.message}}
async function pushCloudState(silent=false){if(!cloudClient||!cloudUser||cloudBusy)return;cloudBusy=true;const status=$('#cloudStatus');if(status)status.textContent='保存中…';const now=new Date().toISOString();const {error}=await cloudClient.from('kimu_snapshots').upsert({user_id:cloudUser.id,payload:cloudEnvelope(),client_updated_at:now},{onConflict:'user_id'});cloudBusy=false;if(error){if(status)status.textContent='保存できなかったよ：'+error.message;return}localStorage.setItem('kimu-last-cloud-sync',now);localStorage.setItem('kimu-local-updated-at',now);$('#saveState').textContent='● クラウド同期済み';if(status)status.textContent='クラウド同期済み：'+new Date(now).toLocaleString('ja-JP');if(!silent)toast('クラウドへ保存したよ')}
async function pullCloudState(silent=false){if(!cloudClient||!cloudUser||cloudBusy)return;cloudBusy=true;const status=$('#cloudStatus');if(status)status.textContent='読込中…';const {data,error}=await cloudClient.from('kimu_snapshots').select('payload,client_updated_at').eq('user_id',cloudUser.id).maybeSingle();cloudBusy=false;if(error){if(status)status.textContent='読み込めなかったよ：'+error.message;return}if(!data){if(status)status.textContent='クラウドにはまだデータがないよ';await pushCloudState(true);return}const last=localStorage.getItem('kimu-last-cloud-sync')||'',local=localStorage.getItem('kimu-local-updated-at')||'',remote=data.client_updated_at||data.payload?.updatedAt||'';if(last&&local>last&&remote>last&&!silent){if(!confirm('この端末とクラウドの両方に変更があるよ。クラウドの内容を優先して読み込む？'))return}if(!last&&state.tasks.length&&remote&&!silent){if(!confirm('この端末の内容をクラウドの内容で置き換える？'))return}cloudApplying=true;applyCloudPayload(data.payload);save();cloudApplying=false;localStorage.setItem('kimu-last-cloud-sync',remote);localStorage.setItem('kimu-local-updated-at',remote);$('#saveState').textContent='● クラウド同期済み';render();if(!silent)toast('クラウドから読み込んだよ')}
async function resumeCloud(){try{await ensureCloudClient();if(cloudUser)await pullCloudState(true)}catch(e){console.warn('auto sync',e)}}
function openImport(mode='import'){const f=$('#importForm');f.innerHTML=`<h2>${mode==='import'?'スプレッドシートから取り込み':'スプレッドシートへ戻す'}</h2><textarea id="sheetText" placeholder="▼▼ 7/1（水）▼▼\nジャンル　仕事内容　時間　進行状況">${mode==='export'?esc(exportTSV()):''}</textarea><menu><button value="cancel" class="secondary">閉じる</button><button type="button" id="sheetAction" class="primary">${mode==='import'?'取り込む':'コピー'}</button></menu>`;$('#sheetAction').onclick=()=>{mode==='import'?importTSV($('#sheetText').value):copyText($('#sheetText').value,'シート用データをコピーしたよ');if(mode==='import')$('#importDialog').close()};$('#importDialog').showModal()}
function importTSV(text){const first=text.split(/\r?\n/).find(Boolean)||'',m=first.match(/(\d{1,2})\/(\d{1,2})/);if(!m)return toast('先頭の日付が見つからないよ');const y=new Date().getFullYear(),date=`${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;const rows=text.split(/\r?\n/).slice(1);rows.forEach(line=>{const c=line.split('\t');if(!c[1]||c.join('').includes('仕事内容'))return;const old=state.tasks.find(t=>t.date===date&&t.title===c[1]);const item=old||{id:uid(),date};Object.assign(item,{category:c[0]||'memo',title:c[1],minutes:+c[2]||null,status:c[3]||'未設定',done:(c[3]||'').includes('完了')});if(!old)state.tasks.push(item)});dirty();render();toast('取り込んだよ')}
function exportTSV(){const d=today(),[y,m,day]=d.split('-');const rows=state.tasks.filter(t=>t.date===d&&!t.deletedAt&&!t.excludeFromSheet).map(t=>[t.category,t.title,t.minutes||'',t.done?'完了':t.status].join('\t'));return [`▼▼ ${+m}/${+day} ▼▼`,...rows].join('\n')}
function downloadBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`kimu-task-${today()}.json`;a.click()}
function restoreBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('復元したよ')}catch{toast('読み込めなかったよ')}};r.readAsText(f)}
function copyText(v,msg){navigator.clipboard.writeText(v).then(()=>toast(msg))}
function toast(v){const t=$('#toast');t.textContent=v;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('open')}
$('#menuButton').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('open')};$('#closeSidebar').onclick=closeSidebar;$('#scrim').onclick=closeSidebar;$('#addButton').onclick=()=>openTask(null,page==='idea'?'idea':page==='memo'?'memo':null);$('#importButton').onclick=()=>openImport('import');$('#exportButton').onclick=()=>openImport('export');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();resumeCloud();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')resumeCloud()});
window.addEventListener('online',resumeCloud);
